branches:
  only:
  - auto
  - master
language: python
cache: pip
addons:
  apt:
    sources:
    - debian-sid  # Grab shellcheck from the Debian repo (o_O)
    packages:
    - shellcheck
install:
  - pip install pre-commit
notifications:
  webhooks: https://habitat-homu.herokuapp.com/travis
script: ./bin/travis.sh
